### ISSUE TITLE
Empty subobjects get converted into "[object Object]"

### ISSUE THREAD

**Issue by PatSmuk360** [snypelife/oxford#28]
![image (1)](https://user-images.githubusercontent.com/19171452/63793989-e8704200-c8ce-11e9-8337-d8f81762de41.png)

**Comment by snypelife** [comment]
Hmmm what would make the most sense in this scenario...

1. Return empty string ("")
2. Return empty object ({})
3. Throw an error ("No empty entries allowed")

I'm leaning toward 3, as it would force you to keep your config clean.
